// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfKy_6S37uXCbHSrvi_ppC3aF1c_-OQA0',
    appId: '1:666850570313:web:d306071ccde4edb8f00f98',
    messagingSenderId: '666850570313',
    projectId: 'fooddelivery-9859e',
    authDomain: 'fooddelivery-9859e.firebaseapp.com',
    storageBucket: 'fooddelivery-9859e.appspot.com',
    measurementId: 'G-6RXTLQ6E5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_iJgo3zbp7jA74k4F-s7qw4PIvZg4N2s',
    appId: '1:666850570313:android:56cd861cabb426e6f00f98',
    messagingSenderId: '666850570313',
    projectId: 'fooddelivery-9859e',
    storageBucket: 'fooddelivery-9859e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtTsl7ecBsnc85D2L_qpb9a5ikC3coHPY',
    appId: '1:666850570313:ios:56b1f187964e313bf00f98',
    messagingSenderId: '666850570313',
    projectId: 'fooddelivery-9859e',
    storageBucket: 'fooddelivery-9859e.appspot.com',
    iosBundleId: 'com.example.fooddelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtTsl7ecBsnc85D2L_qpb9a5ikC3coHPY',
    appId: '1:666850570313:ios:56b1f187964e313bf00f98',
    messagingSenderId: '666850570313',
    projectId: 'fooddelivery-9859e',
    storageBucket: 'fooddelivery-9859e.appspot.com',
    iosBundleId: 'com.example.fooddelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfKy_6S37uXCbHSrvi_ppC3aF1c_-OQA0',
    appId: '1:666850570313:web:7299d885572e2bbff00f98',
    messagingSenderId: '666850570313',
    projectId: 'fooddelivery-9859e',
    authDomain: 'fooddelivery-9859e.firebaseapp.com',
    storageBucket: 'fooddelivery-9859e.appspot.com',
    measurementId: 'G-DJN6JZE109',
  );
}
